// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVUE8o4dE5MnyiQCyj5xUAc4Xhmk1lkE',
    appId: '1:197632354433:web:26ca56978a3a20e9708580',
    messagingSenderId: '197632354433',
    projectId: 'marach-chat-app',
    authDomain: 'marach-chat-app.firebaseapp.com',
    storageBucket: 'marach-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzKJwDflNCmbfYS7vWtA34p2NVU3Ge05A',
    appId: '1:197632354433:android:89fcca300c5e93ac708580',
    messagingSenderId: '197632354433',
    projectId: 'marach-chat-app',
    storageBucket: 'marach-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZXf025S8e3a0BSZVVRnZmsn_okh7h9Gw',
    appId: '1:197632354433:ios:14e7ff94e5982886708580',
    messagingSenderId: '197632354433',
    projectId: 'marach-chat-app',
    storageBucket: 'marach-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZXf025S8e3a0BSZVVRnZmsn_okh7h9Gw',
    appId: '1:197632354433:ios:c04a7f7004e47572708580',
    messagingSenderId: '197632354433',
    projectId: 'marach-chat-app',
    storageBucket: 'marach-chat-app.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
